services:
  postgres:
    image: postgres:15
    container_name: wine-search-instance
    restart: always
    ports:
      - "5432:5432"   # Optional if connecting from outside Docker
    environment:
      POSTGRES_USER: wine_user
      POSTGRES_PASSWORD: wine_pass
      POSTGRES_DB: winesearchdb
    volumes:
      - postgres_data:/var/lib/postgresql/data    # Persistent volume for data

  wine-ai-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wine-api
    ports:
      - "8080:8080"   # Map host:container port
    environment:
      ENV: "dev"
      USE_MOCK: "true"
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
      GOOGLE_API_KEY: "${GOOGLE_API_KEY}"
      GOOGLE_CX: "${GOOGLE_CX}"
      ALLOWED_ORIGINS: "${ALLOWED_ORIGINS}"
      DATABASE_URL: "${DATABASE_URL}"
    depends_on:
      - postgres      # Ensure DB is ready before app starts
    volumes:
      - .:/app        # Mount the app code into the container
      - ~/.cache:/root/.cache  # Avoid re-downloading models

volumes:
  postgres_data: