"""Add grape_varieties to wine_summary

Revision ID: 16f720f64493
Revises: 6095a75cb17d
Create Date: 2025-04-24 02:09:35.045953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f720f64493'
down_revision: Union[str, None] = '6095a75cb17d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wine_summaries', sa.Column('grape_varieties', sa.String(length=255), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wine_summaries', 'grape_varieties')
    # ### end Alembic commands ###
