"""init

Revision ID: 6095a75cb17d
Revises: 
Create Date: 2025-04-22 05:57:59.773282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6095a75cb17d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wine_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wine', sa.String(length=255), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('appearance', sa.Text(), nullable=True),
    sa.Column('nose', sa.Text(), nullable=True),
    sa.Column('palate', sa.Text(), nullable=True),
    sa.Column('quality', sa.String(length=50), nullable=True),
    sa.Column('aging', sa.Text(), nullable=True),
    sa.Column('average_price', sa.String(length=50), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('sat', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reference_source', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wine_summaries_id'), 'wine_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_wine_summaries_wine'), 'wine_summaries', ['wine'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wine_summaries_wine'), table_name='wine_summaries')
    op.drop_index(op.f('ix_wine_summaries_id'), table_name='wine_summaries')
    op.drop_table('wine_summaries')
    # ### end Alembic commands ###
