"""add food pairing tables

Revision ID: d095657511e5
Revises: 84b652a43b3c
Create Date: 2025-06-12 13:17:35.163524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd095657511e5'
down_revision: Union[str, None] = '84b652a43b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_pairing_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wine_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['wine_id'], ['wine_summaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_pairing_categories_id'), 'food_pairing_categories', ['id'], unique=False)
    op.create_table('food_pairing_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('food', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['food_pairing_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_pairing_examples_id'), 'food_pairing_examples', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_pairing_examples_id'), table_name='food_pairing_examples')
    op.drop_table('food_pairing_examples')
    op.drop_index(op.f('ix_food_pairing_categories_id'), table_name='food_pairing_categories')
    op.drop_table('food_pairing_categories')
    # ### end Alembic commands ###
