"""Add base_category to food_pairing_categories

Revision ID: fbf9a1dbee5a
Revises: d095657511e5
Create Date: 2025-06-13 10:53:27.247936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf9a1dbee5a'
down_revision: Union[str, None] = 'd095657511e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema by adding base_category to food_pairing_categories."""
    
    # Step 1: Add the column as nullable
    op.add_column('food_pairing_categories', sa.Column('base_category', sa.String(length=50), nullable=True))

    # Step 2: Backfill with default value 'Other'
    food_pairing_categories = sa.sql.table(
        'food_pairing_categories',
        sa.sql.column('base_category', sa.String)
    )
    op.execute(
        food_pairing_categories.update()
        .where(food_pairing_categories.c.base_category.is_(None))
        .values(base_category='Other')
    )

    # Step 3: Alter column to be non-nullable with server default
    op.alter_column(
        'food_pairing_categories',
        'base_category',
        existing_type=sa.String(length=50),
        nullable=False,
        server_default=sa.text("'Other'")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_pairing_categories', 'base_category')
    # ### end Alembic commands ###
