name: Deploy to Cloud Run (Prod & Test)

on:
  push:
    branches:
      - main
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set environment based on branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "SERVICE_NAME=wine-api" >> $GITHUB_ENV
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          else
            echo "SERVICE_NAME=wine-api-test" >> $GITHUB_ENV
            echo "IMAGE_TAG=test" >> $GITHUB_ENV
          fi

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: "projects/165453885473/locations/global/workloadIdentityPools/github-pool/providers/github-oidc-provider"
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          audience: "https://github.com/chenghwu/wine-ai-app"

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}

      - name: Debug Authentication
        run: |
          gcloud auth list
          gcloud config list

      - name: Build and push image with Cloud Build
        run: |
          gcloud builds submit \
            --tag ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/wine-ai-app/${{ env.SERVICE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/wine-ai-app/${{ env.SERVICE_NAME }}:${{ env.IMAGE_TAG }} \
            --region=${{ secrets.REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --project=${{ secrets.GOOGLE_PROJECT_ID }}
