name: Keep Render Backend Warm

on:
  schedule:
    - cron: "*/10 * * * *" # Every 10 minutes
  workflow_dispatch: # Allow manual trigger too

jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Curl ping to backend
        run: |
          curl -s --retry 5 --retry-delay 10 --max-time 10 https://wine-ai-app.onrender.com/api/db-test || exit 1
